# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-24 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171221_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
